# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIMain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1062, 849)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Plot0 = PlotWidget(self.centralwidget)
        self.Plot0.setObjectName(_fromUtf8("Plot0"))
        self.gridLayout_3.addWidget(self.Plot0, 0, 0, 1, 3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pbGraphInGUI = QtGui.QPushButton(self.centralwidget)
        self.pbGraphInGUI.setMinimumSize(QtCore.QSize(75, 31))
        self.pbGraphInGUI.setMaximumSize(QtCore.QSize(75, 31))
        self.pbGraphInGUI.setObjectName(_fromUtf8("pbGraphInGUI"))
        self.horizontalLayout_8.addWidget(self.pbGraphInGUI)
        spacerItem = QtGui.QSpacerItem(962, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 0, 1, 3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbLSLType = QtGui.QLabel(self.centralwidget)
        self.lbLSLType.setMinimumSize(QtCore.QSize(215, 0))
        self.lbLSLType.setObjectName(_fromUtf8("lbLSLType"))
        self.gridLayout.addWidget(self.lbLSLType, 1, 1, 1, 1)
        self.lbLSLIDX = QtGui.QLabel(self.centralwidget)
        self.lbLSLIDX.setMinimumSize(QtCore.QSize(216, 0))
        self.lbLSLIDX.setObjectName(_fromUtf8("lbLSLIDX"))
        self.gridLayout.addWidget(self.lbLSLIDX, 1, 0, 1, 1)
        self.lbLSLSourceID = QtGui.QLabel(self.centralwidget)
        self.lbLSLSourceID.setMinimumSize(QtCore.QSize(659, 0))
        self.lbLSLSourceID.setObjectName(_fromUtf8("lbLSLSourceID"))
        self.gridLayout.addWidget(self.lbLSLSourceID, 3, 0, 1, 3)
        self.lbLSLFS = QtGui.QLabel(self.centralwidget)
        self.lbLSLFS.setMinimumSize(QtCore.QSize(216, 0))
        self.lbLSLFS.setObjectName(_fromUtf8("lbLSLFS"))
        self.gridLayout.addWidget(self.lbLSLFS, 1, 2, 1, 1)
        self.lbLSLName = QtGui.QLabel(self.centralwidget)
        self.lbLSLName.setMinimumSize(QtCore.QSize(659, 0))
        self.lbLSLName.setObjectName(_fromUtf8("lbLSLName"))
        self.gridLayout.addWidget(self.lbLSLName, 2, 0, 1, 3)
        self.lbLSLUID = QtGui.QLabel(self.centralwidget)
        self.lbLSLUID.setMinimumSize(QtCore.QSize(659, 0))
        self.lbLSLUID.setObjectName(_fromUtf8("lbLSLUID"))
        self.gridLayout.addWidget(self.lbLSLUID, 4, 0, 1, 3)
        self.splitter_5 = QtGui.QSplitter(self.centralwidget)
        self.splitter_5.setMinimumSize(QtCore.QSize(659, 0))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.label_12 = QtGui.QLabel(self.splitter_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cbLSLStream = QtGui.QComboBox(self.splitter_5)
        self.cbLSLStream.setObjectName(_fromUtf8("cbLSLStream"))
        self.gridLayout.addWidget(self.splitter_5, 0, 0, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sbTotalSubchannels = QtGui.QSpinBox(self.centralwidget)
        self.sbTotalSubchannels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbTotalSubchannels.setObjectName(_fromUtf8("sbTotalSubchannels"))
        self.gridLayout_2.addWidget(self.sbTotalSubchannels, 0, 5, 1, 1)
        self.cbChBeg = QtGui.QComboBox(self.centralwidget)
        self.cbChBeg.setObjectName(_fromUtf8("cbChBeg"))
        self.gridLayout_2.addWidget(self.cbChBeg, 1, 2, 1, 2)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 4, 1, 1)
        self.cbChEnd = QtGui.QComboBox(self.centralwidget)
        self.cbChEnd.setObjectName(_fromUtf8("cbChEnd"))
        self.gridLayout_2.addWidget(self.cbChEnd, 1, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 2)
        self.cbSubChBeg = QtGui.QComboBox(self.centralwidget)
        self.cbSubChBeg.setObjectName(_fromUtf8("cbSubChBeg"))
        self.gridLayout_2.addWidget(self.cbSubChBeg, 2, 2, 1, 2)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 4, 1, 1)
        self.cbSubChEnd = QtGui.QComboBox(self.centralwidget)
        self.cbSubChEnd.setObjectName(_fromUtf8("cbSubChEnd"))
        self.gridLayout_2.addWidget(self.cbSubChEnd, 2, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 2)
        self.cbRows = QtGui.QComboBox(self.centralwidget)
        self.cbRows.setObjectName(_fromUtf8("cbRows"))
        self.gridLayout_2.addWidget(self.cbRows, 3, 2, 1, 2)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 4, 1, 1)
        self.cbColumns = QtGui.QComboBox(self.centralwidget)
        self.cbColumns.setObjectName(_fromUtf8("cbColumns"))
        self.gridLayout_2.addWidget(self.cbColumns, 3, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 4, 1, 1)
        self.sbTotalChan = QtGui.QSpinBox(self.centralwidget)
        self.sbTotalChan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbTotalChan.setObjectName(_fromUtf8("sbTotalChan"))
        self.gridLayout_2.addWidget(self.sbTotalChan, 0, 2, 1, 2)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 1, 1, 2)
        self.splitter_4 = QtGui.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.label = QtGui.QLabel(self.splitter_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.dsbFStart = QtGui.QDoubleSpinBox(self.splitter_4)
        self.dsbFStart.setObjectName(_fromUtf8("dsbFStart"))
        self.gridLayout_3.addWidget(self.splitter_4, 3, 2, 1, 1)
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.label_8 = QtGui.QLabel(self.splitter_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.dsbFEnd = QtGui.QDoubleSpinBox(self.splitter_3)
        self.dsbFEnd.setMaximum(1000.0)
        self.dsbFEnd.setObjectName(_fromUtf8("dsbFEnd"))
        self.gridLayout_3.addWidget(self.splitter_3, 4, 2, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pbLaunchGraphs = QtGui.QPushButton(self.centralwidget)
        self.pbLaunchGraphs.setMinimumSize(QtCore.QSize(91, 71))
        self.pbLaunchGraphs.setMaximumSize(QtCore.QSize(91, 71))
        self.pbLaunchGraphs.setObjectName(_fromUtf8("pbLaunchGraphs"))
        self.horizontalLayout_7.addWidget(self.pbLaunchGraphs)
        spacerItem1 = QtGui.QSpacerItem(198, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.tmpIgnore0 = QtGui.QPushButton(self.centralwidget)
        self.tmpIgnore0.setMinimumSize(QtCore.QSize(91, 71))
        self.tmpIgnore0.setMaximumSize(QtCore.QSize(91, 71))
        self.tmpIgnore0.setObjectName(_fromUtf8("tmpIgnore0"))
        self.horizontalLayout_7.addWidget(self.tmpIgnore0)
        spacerItem2 = QtGui.QSpacerItem(198, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pbLaunchPeriodo = QtGui.QPushButton(self.centralwidget)
        self.pbLaunchPeriodo.setMinimumSize(QtCore.QSize(91, 71))
        self.pbLaunchPeriodo.setMaximumSize(QtCore.QSize(91, 71))
        self.pbLaunchPeriodo.setObjectName(_fromUtf8("pbLaunchPeriodo"))
        self.horizontalLayout_7.addWidget(self.pbLaunchPeriodo)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 3, 0, 2, 2)
        self.Plot0.raise_()
        self.label_6.raise_()
        self.cbColumns.raise_()
        self.label_7.raise_()
        self.cbRows.raise_()
        self.label.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pbGraphInGUI.setText(_translate("MainWindow", "Test", None))
        self.lbLSLType.setText(_translate("MainWindow", "Type: ", None))
        self.lbLSLIDX.setText(_translate("MainWindow", "IDX: ", None))
        self.lbLSLSourceID.setText(_translate("MainWindow", "Source ID:", None))
        self.lbLSLFS.setText(_translate("MainWindow", "Sample Rate: ", None))
        self.lbLSLName.setText(_translate("MainWindow", "Name: ", None))
        self.lbLSLUID.setText(_translate("MainWindow", "UID:", None))
        self.label_12.setText(_translate("MainWindow", "Stream: ", None))
        self.label_4.setText(_translate("MainWindow", "to", None))
        self.label_3.setText(_translate("MainWindow", "Subchannels to plot:", None))
        self.label_5.setText(_translate("MainWindow", "to", None))
        self.label_7.setText(_translate("MainWindow", "Rows", None))
        self.label_6.setText(_translate("MainWindow", "Columns", None))
        self.label_10.setText(_translate("MainWindow", "Total Subchannels:", None))
        self.label_9.setText(_translate("MainWindow", "Total Channels:", None))
        self.label_2.setText(_translate("MainWindow", "Channels to plot: ", None))
        self.label.setText(_translate("MainWindow", "F_Start: ", None))
        self.label_8.setText(_translate("MainWindow", "F_End: ", None))
        self.pbLaunchGraphs.setText(_translate("MainWindow", "Launch\n"
"Graphs", None))
        self.tmpIgnore0.setText(_translate("MainWindow", "Launch\n"
"Graphs", None))
        self.pbLaunchPeriodo.setText(_translate("MainWindow", "Launch\n"
"Spectrogram", None))

from pyqtgraph import PlotWidget
